### ISSUE TITLE
Allow overrding PORTSDIR, SVN and other variables

### ISSUE THREAD

**Issue by rodrigc** [Ultima1252/portest#1]
In your scripts:
PORTSDIR
SVN

are hardcoded, and there is no way to override them.  It would be good to
allow overriding these variables.  **ports-mgmt/porttools** allows overriding PORTSDIR for example.

**Comment by rodrigc** [comment]
I ran the script with:

```
sh -x ~/portest/portest -t -T ~/ports_patch.txt
```

and got this:

```
+ PORTEST_VERSION=0.0.3
+ getopts :abj:f:pPrRtTv FLAG
+ TEST_PORTLINT=YES
+ getopts :abj:f:pPrRtTv FLAG
+ TEST_BUILD=YES
+ getopts :abj:f:pPrRtTv FLAG
+ shift 2
+ [ 1 -lt 1 ]
+ SVN=svn
+ SVN_PATCH_ARGS=patch
+ SVN_REVERT_ARGS='revert -R'
+ PORTLINT=portlint
+ PORTLINT_ARGS=-A
+ PORT=port
+ PORT_ARGS=test
+ PORTSDIR=/usr/ports
+ BULK_FILE=build.ports.txt
+ USE_POUDRIERE=YES
+ [ -z '' ]
+ POUDRIERE_JAILS='102amd64 102i386 93amd64 93i386'
+ POUDRIERE_PORTSDIR=/usr/local/poudriere/ports
+ POUDRIERE_PORT=test
+ POUDRIERE=poudriere
+ POUDRIERE_ARGS='bulk -t -C -p test'
+ [ YES '==' YES ]
+ PORTSDIR=/usr/local/poudriere/ports/test
+ pwd
+ CURDIR=/opt2/branches/ports/devel/swig13
+ [ -d /usr/local/poudriere/ports/test ]
+ echo 'PORTSDIR not set or incorrect directory'
PORTSDIR not set or incorrect directory
+ exit 1
```

If I have a machine where I never ran poudriere, how do I populate
**/usr/local/poudriere/ports/test** ?

**Comment by Ultima1252** [comment]
Yes, This is something I'm planning on adding, when I get some more time. (maybe this weekend)  I change the port tree to default/test often and didn't realize that it was on test when tagging so I'm sorry.
I will be changing it back to default and adding an option to change the port tree.

**Comment by Ultima1252** [comment]
Change POUDRIERE_PORT="test" to "default"

Have not yet added a config file to portest. This is something I'm still contemplating on and decided to leave it out for simplicity.This may change in the future.

**Comment by t-zuehlsdorff** [comment]
Hello,

have a look at my pull request:
https://github.com/Ultima1252/portest/pull/3

**Comment by t-zuehlsdorff** [comment]
Hello Ricky,

as i changed the version too in my update, you should create a new release 0.0.4 :)

Greetings,
Torsten

**Comment by Ultima1252** [comment]
Done! I wasn't sure if it was possible in the webui, but I found it! =D
