### ISSUE TITLE
git support

### ISSUE THREAD

**Issue by rodrigc** [Ultima1252/portest#2]
Sometimes it is useful to obtain the ports tree from git, such as
    https://github.com/freebsd/freebsd-ports

Adding git support to portest would be nice.

You could use commands like
git clone --depth 1
git pull 
git reset --hard
git clean -fd -f

**Comment by Ultima1252** [comment]
Do not have much experience with git, so this is helpful. This will be added in the near future. Thanks for the feedback! =]

**Comment by t-zuehlsdorff** [comment]
@rodrigc 
Do you just want to obtain the portstree from git or do you also want to apply git patches?

**Comment by rodrigc** [comment]
Yes, get the tree using git **and** apply git-style patches

**Comment by Ultima1252** [comment]
Mostly have this finished added this request. I am wondering however, create a repo with poudriere support, stand alone for portest, or both?

**Comment by rodrigc** [comment]
I would say do both.
(1)  Poudriere has command-line options for checking out a repo from git, so would be good to support
       that.
(2)  For my scripting, I need/want the repo to be checked out **outside** of poudriere.  So would be good to support that also.

**Comment by Ultima1252** [comment]
Working on poudriere, this shouldn't be too difficult. 2 is done for the most part. I need to do a little more testing before making a new tag. Right now, after creating the repo the script will exit, is this behavior acceptable? It shouldn't be too hard to change this if needed.

**Comment by Ultima1252** [comment]
Finished adding git support!  I am really starting to like how portest is feeling. Keep the feedback coming please =D
